## Упражнение № 1

Создайте Series из каждого из элементов: списка, ndarray и словаря.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [1]:
import pandas as pd
import numpy as np

# Создаем данные
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

# Создаем Series из списка
series_from_list = pd.Series(mylist)
print("Series из списка:")
print(series_from_list)

# Создаем Series из ndarray
series_from_array = pd.Series(myarr)
print("\nSeries из ndarray:")
print(series_from_array)

# Создаем Series из словаря
series_from_dict = pd.Series(mydict)
print("\nSeries из словаря:")
print(series_from_dict)


Series из списка:
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

Series из ndarray:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

Series из словаря:
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## Упражнение № 2

Преобразуйте `ser` в датафрейм с его индексом в качестве еще одного столбца датафрейма.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
```

In [2]:
import pandas as pd
import numpy as np

# Создаем данные
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

# Преобразуем Series в DataFrame
df = ser.reset_index()  # используем reset_index() для сброса индекса
df.columns = ['Index', 'Value']  # переименуем столбцы

# Выводим результат
print(df)


   Index  Value
0      a      0
1      b      1
2      c      2
3      e      3
4      d      4
5      f      5
6      g      6
7      h      7
8      i      8
9      j      9
10     k     10
11     l     11
12     m     12
13     n     13
14     o     14
15     p     15
16     q     16
17     r     17
18     s     18
19     t     19
20     u     20
21     v     21
22     w     22
23     x     23
24     y     24
25     z     25


## Упражнение № 3

Объедините `ser1` и `ser2`, чтобы сформировать датафрейм.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [3]:
import pandas as pd
import numpy as np

# Создаем данные для ser1
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mydict)

# Создаем данные для ser2 (например, можно использовать другой набор значений)
mylist2 = list('zyxwvutsrqponmlkjihgfedcba')  # инвертируем порядок
myarr2 = np.arange(26, 52)  # новые значения
mydict2 = dict(zip(mylist2, myarr2))
ser2 = pd.Series(mydict2)

# Объединяем ser1 и ser2 в датафрейм
df = pd.DataFrame({'Column1': ser1, 'Column2': ser2})

# Выводим результат
print(df)


   Column1  Column2
a        0       51
b        1       50
c        2       49
d        4       48
e        3       47
f        5       46
g        6       45
h        7       44
i        8       43
j        9       42
k       10       41
l       11       40
m       12       39
n       13       38
o       14       37
p       15       36
q       16       35
r       17       34
s       18       33
t       19       32
u       20       31
v       21       30
w       22       29
x       23       28
y       24       27
z       25       26


## Упражнение № 4

Добавьте имя ряда  `ser`, назвав его `latin_letters`.

Пример входных данных:

```python
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
```

In [4]:
import pandas as pd

# Создаем серию
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

# Присваиваем имя рядy
ser.name = 'latin_letters'

# Выводим результат
print(ser)


0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, dtype: object


## Упражнение № 5

Из `ser1` удалите элементы, присутствующие в `ser2`.

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [5]:
import pandas as pd

# Определяем серии
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Удаляем элементы из ser1, которые присутствуют в ser2
ser1_filtered = ser1[~ser1.isin(ser2)]

# Выводим результат
print(ser1_filtered)


0    1
1    2
2    3
dtype: int64


## Упражнение № 6

Получить все элементы `ser1` и `ser2`, которые не являются общими для обоих рядов.

Пример входных данных:

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [6]:
import pandas as pd

# Определяем серии
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Объединяем две серии
combined = pd.concat([ser1, ser2])

# Удаляем общие элементы
unique_elements = combined[~combined.isin(combined[combined.duplicated()])]

# Выводим результат
print(unique_elements)


0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


## Упражнение № 7

Вычислите минимальное значение, 25-й процентиль, медиану, 75-й процентиль и максимальное значение `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.normal(10, 5, 25))
```

In [7]:
import pandas as pd
import numpy as np

# Генерируем случайную серию
ser = pd.Series(np.random.normal(10, 5, 25))

# Вычисляем необходимые статистики
min_value = ser.min()
percentile_25 = ser.quantile(0.25)
median_value = ser.median()
percentile_75 = ser.quantile(0.75)
max_value = ser.max()

# Выводим результаты
print(f"Минимальное значение: {min_value}")
print(f"25-й процентиль: {percentile_25}")
print(f"Медиана: {median_value}")
print(f"75-й процентиль: {percentile_75}")
print(f"Максимальное значение: {max_value}")


Минимальное значение: 0.999099561674818
25-й процентиль: 7.49788000720637
Медиана: 9.803168799233797
75-й процентиль: 12.071145483539953
Максимальное значение: 20.571688465709187


## Упражнение № 8

Вычислите частоту встречаемости каждого уникального значения `ser`.

Пример входных данных:

```python
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```


In [8]:
import pandas as pd
import numpy as np

# Генерируем случайную серию с символами от 'a' до 'h'
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

# Вычисляем частоту встречаемости уникальных значений
frequency_counts = ser.value_counts()

# Выводим результаты
print(frequency_counts)


a    7
g    7
e    5
f    3
h    3
b    3
c    2
Name: count, dtype: int64


## Упражнение № 9

Из `ser` оставить 2 наиболее часто встречающихся элемента без изменений, а все остальные заменить на `Прочее`.

Пример входных данных:

```python
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```

In [9]:
import pandas as pd
import numpy as np

# Устанавливаем случайное состояние для воспроизводимости
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Находим 2 наиболее часто встречающихся элемента
top_two = ser.value_counts().index[:2]

# Заменяем все значения, которые не относятся к топ-2, на прочее
ser_modified = ser.where(ser.isin(top_two), "Прочее")

# Выводим результаты
print("Исходная серия:")
print(ser)
print("\nИзмененная серия:")
print(ser_modified)


Исходная серия:
0     1
1     4
2     1
3     3
4     1
5     4
6     1
7     3
8     1
9     1
10    2
11    4
dtype: int32

Измененная серия:
0          1
1          4
2          1
3     Прочее
4          1
5          4
6          1
7     Прочее
8          1
9          1
10    Прочее
11         4
dtype: object


## Упражнение № 10

Разбейте ряд `ser` на 10 равных децилей и замените значения на название дециля.

Пример входных данных:

```python
ser = pd.Series(np.random.random(20))
```

Пример выходных данных:

```python
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
```

In [10]:
import pandas as pd
import numpy as np

# Генерируем случайную серию из 20 значений
ser = pd.Series(np.random.random(20))

# Разбиваем на 10 децилей и заменяем значения на названия децилей
déciles = pd.qcut(ser, 10, labels=[f'{i+1}th' for i in range(10)])

# Выводим результаты
print("Исходная серия:")
print(ser)
print("\nСерия с децилями:")
print(déciles)


Исходная серия:
0     0.382245
1     0.702007
2     0.448655
3     0.026556
4     0.345973
5     0.710589
6     0.919692
7     0.441007
8     0.425828
9     0.589554
10    0.349082
11    0.529662
12    0.500923
13    0.477455
14    0.773648
15    0.115225
16    0.060087
17    0.706741
18    0.629349
19    0.632216
dtype: float64

Серия с децилями:
0      3th
1      8th
2      5th
3      1th
4      2th
5      9th
6     10th
7      4th
8      4th
9      7th
10     3th
11     6th
12     6th
13     5th
14    10th
15     2th
16     1th
17     9th
18     7th
19     8th
dtype: category
Categories (10, object): ['1th' < '2th' < '3th' < '4th' ... '7th' < '8th' < '9th' < '10th']


## Упражнение № 11

Переформируйте ряд `ser` в датафрейм с 7 строками и 5 столбцами

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 35))
```

In [11]:
import pandas as pd
import numpy as np

# Генерируем случайную серию из 35 целых чисел от 1 до 9
ser = pd.Series(np.random.randint(1, 10, 35))

# Преобразуем серию в датафрейм с 7 строками и 5 столбцами
df = pd.DataFrame(ser.values.reshape(7, 5))

# Выводим результат
print("Исходная серия:")
print(ser)
print("\nДатафрейм:")
print(df)


Исходная серия:
0     5
1     6
2     4
3     9
4     2
5     4
6     9
7     9
8     6
9     2
10    2
11    7
12    4
13    1
14    1
15    3
16    2
17    8
18    5
19    9
20    4
21    5
22    2
23    9
24    8
25    3
26    5
27    9
28    8
29    7
30    4
31    3
32    8
33    4
34    7
dtype: int32

Датафрейм:
   0  1  2  3  4
0  5  6  4  9  2
1  4  9  9  6  2
2  2  7  4  1  1
3  3  2  8  5  9
4  4  5  2  9  8
5  3  5  9  8  7
6  4  3  8  4  7


## Упражнение № 12

Найти позиции чисел, кратных 3, из ряда `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 7))
```

In [12]:
import pandas as pd
import numpy as np

# Генерируем случайную серию из 7 целых чисел от 1 до 9
ser = pd.Series(np.random.randint(1, 10, 7))

# Находим позиции чисел, кратных 3
positions = ser[ser % 3 == 0].index.tolist()

# Выводим результат
print("Исходная серия:")
print(ser)
print("\nПозиции чисел, кратных 3:")
print(positions)


Исходная серия:
0    5
1    4
2    8
3    1
4    1
5    4
6    3
dtype: int32

Позиции чисел, кратных 3:
[6]


## Упражнение № 13

Из `ser` извлечь элементы, находящиеся на позициях в списке `pos`.

Пример входных данных:

```python
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
```


In [13]:
import pandas as pd

# Создаем серию из букв английского алфавита
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

# Заданный список позиций
pos = [0, 4, 8, 14, 20]

# Извлекаем элементы по указанным позициям
extracted_elements = ser.iloc[pos]

# Выводим результат
print("Исходная серия:")
print(ser)
print("\nИзвлеченные элементы на позициях {}:".format(pos))
print(extracted_elements)


Исходная серия:
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

Извлеченные элементы на позициях [0, 4, 8, 14, 20]:
0     a
4     e
8     i
14    o
20    u
dtype: object


## Упражнение № 14

Объедините `ser1` и `ser2` по вертикали и горизонтали (чтобы сформировать датафрейм).

Пример входных данных:

```python
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [14]:
import pandas as pd

# Создаем две серии
ser1 = pd.Series(range(5))  # Серия с числами от 0 до 4
ser2 = pd.Series(list('abcde'))  # Серия с буквами a, b, c, d, e

# Объединение по вертикали (конкатенация)
vertical_concat = pd.concat([ser1, ser2], axis=0)
print("Объединение по вертикали:")
print(vertical_concat)

# Преобразуем серии в датафреймы для горизонтального объединения
df1 = ser1.to_frame(name='Numbers')  # Преобразования в датафрейм с названием столбца
df2 = ser2.to_frame(name='Letters')

# Объединение по горизонтали
horizontal_concat = pd.concat([df1, df2], axis=1)
print("\nОбъединение по горизонтали:")
print(horizontal_concat)


Объединение по вертикали:
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

Объединение по горизонтали:
   Numbers Letters
0        0       a
1        1       b
2        2       c
3        3       d
4        4       e


## Упражнение № 15

Получите позиции элементов `ser2` в `ser1` в виде списка.

Пример входных данных:

```python
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
```

In [15]:
import pandas as pd

# Определяем серии
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Получаем позиции элементов ser2 в ser1
positions = [ser1[ser1 == value].index.tolist()[0] for value in ser2 if value in ser1.values]

# Выводим результат
print("Позиции элементов из ser2 в ser1:", positions)


Позиции элементов из ser2 в ser1: [5, 4, 0, 8]


## Упражнение № 16

Вычислить среднеквадратическую ошибку рядов `truth` и `pred`.

Пример входных данных:

```python
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
```

In [16]:
import pandas as pd
import numpy as np

# Определяем серии
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Вычисляем среднеквадратическую ошибку
mse = ((truth - pred) ** 2).mean()

# Выводим результат
print("Среднеквадратическая ошибка:", mse)


Среднеквадратическая ошибка: 0.34296202823111327


## Упражнение № 17

В каждом слове `ser` поставьте первый символ каждого слова в верхний регистр.

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```


In [17]:
import pandas as pd

# Определяем серию
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Изменяем первый символ каждого слова на заглавный
capitalized_ser = ser.str.capitalize()

# Выводим результат
print(capitalized_ser)


0     How
1      To
2    Kick
3    Ass?
dtype: object


## Упражнение № 18

В каждом слове `ser` посчитайте число символов.

Пример входных данных:

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [18]:
import pandas as pd

# Определяем серию
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Считаем количество символов в каждом слове
lengths = ser.str.len()

# Выводим результат
print(lengths)


0    3
1    2
2    4
3    4
dtype: int64


## Упражнение № 19

Вычислите разность разностей между последовательно идущими числами в `ser`.

Пример входных данных:

```python
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
```

Пример выходных данных:

```
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]
```

In [19]:
import pandas as pd

# Определяем серию
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

# Вычисляем разности между последовательно идущими числами
first_difference = ser.diff()

# Вычисляем разности между разностями
second_difference = first_difference.diff()

# Выводим результаты
print(first_difference)
print(second_difference)


0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64


## Упражнение № 20

Преобразуйте строковое представление дат в `datetime64`.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [24]:
import pandas as pd

# Определяем серию с датами в строковом формате
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Преобразуем строки в datetime64 с обработкой ошибок
datetime_series = pd.to_datetime(ser, errors='coerce')

# Выводим результаты
print(datetime_series)


0   2010-01-01
1          NaT
2          NaT
3          NaT
4          NaT
5          NaT
dtype: datetime64[ns]


## Упражнение № 21

Получите из `ser` день месяца, номер недели, день года и день недели.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [23]:
import pandas as pd

# Определяем серию с датами в строковом формате
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Преобразуем строки в datetime64 с обработкой ошибок
datetime_series = pd.to_datetime(ser, errors='coerce')

# Извлекаем необходимые значения
day_of_month = datetime_series.dt.day
week_number = datetime_series.dt.isocalendar().week
day_num_of_year = datetime_series.dt.dayofyear
day_of_week = datetime_series.dt.day_name()

# Выводим результаты
print("Date: ", list(day_of_month))
print("Week number: ", list(week_number))
print("Day num of year: ", list(day_num_of_year))
print("Day of week: ", list(day_of_week))


Date:  [1.0, nan, nan, nan, nan, nan]
Week number:  [np.uint32(53), <NA>, <NA>, <NA>, <NA>, <NA>]
Day num of year:  [1.0, nan, nan, nan, nan, nan]
Day of week:  ['Friday', nan, nan, nan, nan, nan]


## Упражнение № 21

Получите из `ser` день месяца, номер недели, день года и день недели.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [82]:
import pandas as pd

# Исходные данные
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Преобразуем строки в datetime64, убираем infer_datetime_format
datetime_series = pd.to_datetime(ser, errors='coerce')

# Извлекаем необходимые значения
day_of_month = datetime_series.dt.day.tolist()  # День месяца
week_number = datetime_series.dt.isocalendar().week.tolist()  # Номер недели
day_num_of_year = datetime_series.dt.dayofyear.tolist()  # День года
day_of_week = datetime_series.dt.day_name().tolist()  # День недели

# Выводим результаты
print("Date: ", day_of_month)
print("Week number: ", week_number)
print("Day num of year: ", day_num_of_year)
print("Day of week: ", day_of_week)


Date:  [1.0, nan, nan, nan, nan, nan]
Week number:  [53, <NA>, <NA>, <NA>, <NA>, <NA>]
Day num of year:  [1.0, nan, nan, nan, nan, nan]
Day of week:  ['Friday', nan, nan, nan, nan, nan]


## Упражнение № 22

Замените элементы `ser` на даты, начинающиеся с 4-го числа соответствующего месяца.

Пример входных данных:

```python
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
```

Пример выходных данных:

```
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]
```

In [27]:
import pandas as pd

# Создаем серию с месяцами и годами в строковом формате
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Преобразуем строки в datetime, устанавливая день равным 4
dates = pd.to_datetime(ser + ' 4', format='%b %Y %d')

# Выводим результат
print(dates)


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


## Упражнение № 23

Из `ser` извлеките слова, содержащие не менее 2 гласных букв.

Пример входных данных:

```python
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
```

Пример выходных данных:

```
0     Apple
1    Orange
4     Money
dtype: object
```

In [28]:
import pandas as pd

# Определяем серию
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Определяем регулярное выражение для поиска слов с 2 и более гласными
vowel_pattern = r'[AEIOUaeiou].*[AEIOUaeiou]'

# Извлекаем слова, соответствующие шаблону
filtered_words = ser[ser.str.contains(vowel_pattern)]

# Выводим результат
print(filtered_words)


0     Apple
1    Orange
4     Money
dtype: object


## Упражнение № 24

Извлеките корректные адреса электронной почты из ряда `emails`. Шаблон регулярного выражения для корректных адресов электронной почты приведен в качестве образца.

Пример входных данных:

```python
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
```

Пример выходных данных:

```
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
```

In [30]:
import pandas as pd

# Определяем серию с электронными адресами
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

# Шаблон регулярного выражения для корректных адресов электронной почты с группами
pattern = r'([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})'

# Извлекаем адреса электронной почты
extracted_emails = emails.str.extract(pattern)

# Убираем NaN значения и оставляем только корректные адреса
valid_emails = extracted_emails.dropna()[0]

# Выводим результат
print(valid_emails)


1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
Name: 0, dtype: object


## Упражнение № 25

Вычислить среднее значение веса в `weights` для каждого фрукта из `fruit`.

Пример входных данных:

```python
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
```

Пример выходных данных:

```python
# values can change due to randomness
apple     6.0
banana    4.0
carrot    5.8
dtype: float64
```

In [31]:
import pandas as pd
import numpy as np

# Генерируем фрукты и веса
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Объединяем фрукты и веса в DataFrame
data = pd.DataFrame({'fruit': fruit, 'weight': weights})

# Вычисляем среднее значение веса для каждого фрукта
average_weights = data.groupby('fruit')['weight'].mean()

# Выводим результат
print(average_weights)


fruit
apple     4.00
banana    9.00
carrot    5.25
Name: weight, dtype: float64


## Упражнение № 26

Вычислить [евклидово расстояние](https://en.wikipedia.org/wiki/Euclidean_distance) между векторами $p$ и $q$, не используя встроенную формулу.

Пример входных данных:

```python
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
```

Пример выходных данных:

```
18.165
```

In [32]:
import pandas as pd
import numpy as np

# Задаем векторы p и q
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Вычисляем евклидово расстояние
distance = np.sqrt(((p - q) ** 2).sum())

# Выводим результат
print(f"{distance:.3f}")


18.166


## Упражнение № 27

Получите позиции пиков (значений, окруженных с двух сторон меньшими значениями) в `ser`.

Пример входных данных:

```python
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
```

Пример выходных данных:

```
array([1, 5, 7])
```

In [33]:
import pandas as pd
import numpy as np

# Задаем серию
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Находим позиции пиков
peaks = []
for i in range(1, len(ser) - 1):
    if ser[i] > ser[i - 1] and ser[i] > ser[i + 1]:
        peaks.append(i)

# Преобразуем список в массив и выводим результат
peaks_array = np.array(peaks)
print(peaks_array)


[1 5 7]


## Упражнение № 28

Замените пробелы в `my_str` на наименее часто встречающийся символ.

Пример входных данных:

```python
my_str = 'dbc deb abed gade'
```

Пример выходных данных:

```
'dbccdebcabedcgade'  # least frequent is 'c'
```

In [34]:
from collections import Counter

# Задаем строку
my_str = 'dbc deb abed gade'

# Считаем частоту символов, игнорируя пробелы
char_count = Counter(my_str.replace(' ', ''))

# Находим наименее часто встречающийся символ
least_frequent_char = min(char_count, key=char_count.get)

# Заменяем пробелы на наименее часто встречающийся символ
result_str = my_str.replace(' ', least_frequent_char)

# Выводим результат
print(result_str)


dbccdebcabedcgade


## Упражнение № 29

Создайте временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа

Пример выходных данных:

```
# values can be random
2000-01-01    4
2000-01-08    1
2000-01-15    8
2000-01-22    4
2000-01-29    4
2000-02-05    2
2000-02-12    4
2000-02-19    9
2000-02-26    6
2000-03-04    6
```

In [35]:
import pandas as pd
import numpy as np

# Устанавливаем начальную дату
start_date = '2000-01-01'

# Генерируем 10 субботних дней начиная с начальной даты
date_rng = pd.date_range(start=start_date, periods=10, freq='W-SAT')

# Генерируем случайные значения
values = np.random.randint(1, 10, size=len(date_rng))  # значения от 1 до 9

# Создаем временной ряд
time_series = pd.Series(data=values, index=date_rng)

# Выводим временной ряд
print(time_series)


2000-01-01    3
2000-01-08    7
2000-01-15    1
2000-01-22    9
2000-01-29    2
2000-02-05    8
2000-02-12    6
2000-02-19    7
2000-02-26    9
2000-03-04    8
Freq: W-SAT, dtype: int32


## Упражнение № 30

В `ser` отсутствуют некоторые даты и значения. Сделайте так, чтобы все отсутствующие даты появились и заполнились значением из предыдущей даты.

Пример входных данных:

```python
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64
```

Пример выходных данных:

```
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
```

In [36]:
import pandas as pd
import numpy as np

# Создаем серию с данными
ser = pd.Series([1, 10, 3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print("Original Series:")
print(ser)

# Создаем полный диапазон дат от минимальной до максимальной даты в серии
full_range = pd.date_range(start=ser.index.min(), end=ser.index.max())

# Перемещаем серию по полному диапазону дат
ser_full = ser.reindex(full_range)

# Заполняем пропущенные значения предыдущими
ser_filled = ser_full.fillna(method='ffill')

# Выводим результат
print("\nFilled Series:")
print(ser_filled)


Original Series:
2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

Filled Series:
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64


C:\Users\Диана Долганова\AppData\Local\Temp\ipykernel_4472\2834950698.py:16: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ser_filled = ser_full.fillna(method='ffill')


## Упражнение № 31

Вычислите автокорреляции для первых 10 лагов `ser`. Определите, какой из лагов имеет наибольшую корреляцию. (см. также [Модель авторегрессии и распределённого лага — Википедия](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C_%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%B8_%D0%B8_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BB%D0%B0%D0%B3%D0%B0))

Пример входных данных:

```python
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
```

Пример выходных данных:

```
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [37]:
import pandas as pd
import numpy as np

# Создаем серию с случайными данными
np.random.seed(42)  # Для воспроизводимости
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Вычисляем автокорреляции для первых 10 лагов
autocorrelations = [ser.autocorr(lag) for lag in range(1, 11)]

# Находим лаг с наибольшей корреляцией
max_lag = np.argmax(autocorrelations) + 1  # +1, так как индексы начинаются с 0
max_correlation = autocorrelations[max_lag - 1]  # Получаем значение корреляции

# Выводим результаты
print("Autocorrelations for the first 10 lags:")
print(autocorrelations)
print(f"Lag having highest correlation: {max_lag} (Correlation: {max_correlation})")


Autocorrelations for the first 10 lags:
[np.float64(-0.03581945085095045), np.float64(-0.3554658547577508), np.float64(0.2435387274242055), np.float64(-0.22886231778550958), np.float64(-0.0610049216621662), np.float64(0.10261951291041886), np.float64(-0.5934975070400584), np.float64(-0.12621105571001182), np.float64(0.32558148560211725), np.float64(-0.027390597912749007)]
Lag having highest correlation: 9 (Correlation: 0.32558148560211725)


## Упражнение № 32

Импортируйте каждую 50-ю строку набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [38]:
import pandas as pd

# Загрузка данных
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
data = pd.read_csv(url)

# Выбор каждой 50-й строки
data_every_50th = data.iloc[::50]

# Выводим результат
print(data_every_50th)


         crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
50    0.08873  21.0   5.64     0  0.439  5.963   45.7  6.8147    4  243   
100   0.14866   0.0   8.56     0  0.520  6.727   79.9  2.7778    5  384   
150   1.65660   0.0  19.58     0  0.871  6.122   97.3  1.6180    5  403   
200   0.01778  95.0   1.47     0  0.403  7.135   13.9  7.6534    3  402   
250   0.14030  22.0   5.86     0  0.431  6.487   13.0  7.3967    7  330   
300   0.04417  70.0   2.24     0  0.400  6.871   47.4  7.8278    5  358   
350   0.06211  40.0   1.25     0  0.429  6.490   44.4  8.7921    1  335   
400  25.04610   0.0  18.10     0  0.693  5.987  100.0  1.5888   24  666   
450   6.71772   0.0  18.10     0  0.713  6.749   92.6  2.3236   24  666   
500   0.22438   0.0   9.69     0  0.585  6.027   79.7  2.4982    6  391   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45

## Упражнение № 33

Импортируйте набор данных [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv), но при импорте измените столбец `'medv'` (*median house value*) так, чтобы значения < 25 стали `Low`, а > 25 - `High`.

In [39]:
import pandas as pd

# Загрузка данных
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
data = pd.read_csv(url)

# Замена значений в столбце 'medv'
data['medv'] = data['medv'].apply(lambda x: 'Low' if x < 25 else 'High')

# Выводим результат
print(data.head())  # Показываем первые несколько строк для проверки


      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


## Упражнение № 34

Создайте датафрейм со строками в виде шагов (интервалов) заданного ряда

Пример входных данных:

```python
L = pd.Series(range(15))
```

Пример выходных данных:

```
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```


In [40]:
import pandas as pd

# Исходные данные
L = pd.Series(range(15))

# Создание датафрейма со строками в виде шагов
step_size = 2  # Размер шага
window_size = 4  # Размер окна
data = [L[i:i + window_size].values for i in range(0, len(L) - window_size + 1, step_size)]

# Создаем датафрейм
df = pd.DataFrame(data)

# Выводим результат
print(df)


    0   1   2   3
0   0   1   2   3
1   2   3   4   5
2   4   5   6   7
3   6   7   8   9
4   8   9  10  11
5  10  11  12  13


## Упражнение № 35

Импортируйте столбцы 'crim' и 'medv' из набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.


In [41]:
import pandas as pd

# Загрузка данных
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
data = pd.read_csv(url, usecols=['crim', 'medv'])

# Выводим результат
print(data.head())  # Показываем первые несколько строк для проверки


      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


## Упражнение № 36

Получите количество строк, столбцов, тип данных и суммарную статистику каждого столбца набора данных [Cars93](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv). Также получите эквивалент датафрейма в виде numpy-массива и списка.


In [42]:
import pandas as pd

# Загрузка данных
url = "https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv"
data = pd.read_csv(url)

# Получение количества строк и столбцов
num_rows, num_columns = data.shape
print(f"Количество строк: {num_rows}, Количество столбцов: {num_columns}")

# Получение типов данных каждого столбца
data_types = data.dtypes
print("\nТипы данных каждого столбца:\n", data_types)

# Получение суммарной статистики для каждого столбца
summary_statistics = data.describe(include='all')
print("\nСуммарная статистика каждого столбца:\n", summary_statistics)

# Преобразование датафрейма в numpy-массив
numpy_array = data.to_numpy()
print("\nNumpy массив:\n", numpy_array)

# Преобразование датафрейма в список
list_data = data.values.tolist()
print("\nСписок:\n", list_data)


Количество строк: 93, Количество столбцов: 27

Типы данных каждого столбца:
 Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

Суммарная статистика каждого столбца:
        Manufacturer    Model     Type  Min.Price      Price

## Упражнение № 37

Извлеките номер строки и столбца конкретной ячейки по заданному критерию.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

*Какой производитель, модель и тип имеет наибольшую цену в `Price`? Каков номер строки и столбца ячейки с наибольшим значением `Price`?*

In [43]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Нахождение строки с наибольшей ценой
max_price_row = df.loc[df['Price'].idxmax()]

# Извлечение информации
manufacturer = max_price_row['Manufacturer']
model = max_price_row['Model']
car_type = max_price_row['Type']
max_price_index = df['Price'].idxmax()  # Номер строки
max_price_column = df.columns.get_loc('Price')  # Номер столбца

# Вывод результатов
print(f"Производитель: {manufacturer}")
print(f"Модель: {model}")
print(f"Тип: {car_type}")
print(f"Номер строки: {max_price_index}")
print(f"Номер столбца (Price): {max_price_column}")


Производитель: Mercedes-Benz
Модель: 300E
Тип: Midsize
Номер строки: 58
Номер столбца (Price): 4


## Упражнение № 38

Переименуйте в `df` столбец `Type` в `CarType` и замените `.` в именах столбцов на `_`.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
#> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
#>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
#>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

Пример выходных данных:

```python
print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

In [44]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Переименование столбца 'Type' в 'CarType'
df.rename(columns={'Type': 'CarType'}, inplace=True)

# Замена '.' на '_'
df.columns = df.columns.str.replace('.', '_', regex=False)

# Вывод измененных имен столбцов
print(df.columns)


Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Упражнение № 39

Проверьте, нет ли в `df` отсутствующих значений.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [45]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Проверка на наличие отсутствующих значений
missing_values = df.isnull().sum()

# Вывод результатов
print(missing_values[missing_values > 0])  # Показывает только те столбцы, где есть пропуски


Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64


## Упражнение № 40

Подсчитайте количество пропущенных значений в каждом столбце `df`. Какой столбец имеет наибольшее число пропущенных значений?

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [46]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Подсчет пропущенных значений в каждом столбце
missing_counts = df.isnull().sum()

# Вывод общего количества пропущенных значений по каждому столбцу
print("Количество пропущенных значений в каждом столбце:\n", missing_counts)

# Находим столбец с наибольшим количеством пропущенных значений
max_missing_column = missing_counts.idxmax()
max_missing_value = missing_counts.max()

print(f"\nСтолбец с наибольшим количеством пропущенных значений: '{max_missing_column}' ({max_missing_value} пропусков)")


Количество пропущенных значений в каждом столбце:
 Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Столбец с наибольшим количеством пропущенных значений: 'AirBags' (38 пропусков)


## Упражнение № 41

Замените отсутствующие значения в столбцах `Min.Price` и `Max.Price` на соответствующие им средние значения.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [48]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Вычисление средних значений по столбцам Min.Price и Max.Price
mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

# Замена пропущенных значений на вычисленные средние
df['Min.Price'] = df['Min.Price'].fillna(mean_min_price)
df['Max.Price'] = df['Max.Price'].fillna(mean_max_price)

# Проверка, что пропуски заменены
print("Количество пропущенных значений после замены:\n", df[['Min.Price', 'Max.Price']].isnull().sum())


Количество пропущенных значений после замены:
 Min.Price    0
Max.Price    0
dtype: int64


## Упражнение № 42

В `df` с помощью метода `apply` замените недостающие значения в `Min.Price` на среднее значение столбца, а в `Max.Price` — на медиану столбца.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

[Подсказка на StackOverflow](https://stackoverflow.com/questions/32437435/passing-additional-arguments-to-python-pandas-dataframe-apply)

In [49]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Вычисление среднего и медианного значений
mean_min_price = df['Min.Price'].mean()
median_max_price = df['Max.Price'].median()

# Функция для замены NaN на среднее/медиану
def fill_na(series, fill_value):
    return series.apply(lambda x: fill_value if pd.isna(x) else x)

# Применение функции к столбцам
df['Min.Price'] = fill_na(df['Min.Price'], mean_min_price)
df['Max.Price'] = fill_na(df['Max.Price'], median_max_price)

# Проверка, что пропуски заменены
print("Количество пропущенных значений после замены:\n", df[['Min.Price', 'Max.Price']].isnull().sum())


Количество пропущенных значений после замены:
 Min.Price    0
Max.Price    0
dtype: int64


## Упражнение № 43

Получите первый столбец (`a`) в `df` в виде датафрейма (а не в виде ряда).

Пример входных данных:

```python
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```


In [50]:
import pandas as pd
import numpy as np

# Создание исходного датафрейма
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Получение первого столбца 'a' в виде датафрейма
first_column_df = df[['a']]

# Проверка результата
print(first_column_df)
print(type(first_column_df))  # Проверка типа переменной


    a
0   0
1   5
2  10
3  15
<class 'pandas.core.frame.DataFrame'>


# Упражнение № 44

1. В `df` поменяйте местами столбцы `'a'` и `'c'`.
2. Создайте обобщенную функцию для обмена данными между двумя столбцами без фиксированного задания имен столбцов.
3. Отсортируйте столбцы в обратном алфавитном порядке, т.е. от столбца `'e'` до столбца `'a'`.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```


In [51]:
import pandas as pd
import numpy as np

# Создание исходного датафрейма
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# 1. Меняем местами столбцы 'a' и 'c'
df[['a', 'c']] = df[['c', 'a']]

# Вывод измененного датафрейма
print("После обмена 'a' и 'c':")
print(df)

# 2. Функция для обмена данными между двумя столбцами
def swap_columns(df, col1, col2):
    df[[col1, col2]] = df[[col2, col1]]

# Пример использования функции для обмена 'b' и 'd'
swap_columns(df, 'b', 'd')

# Вывод измененного датафрейма после использования функции
print("\nПосле обмена 'b' и 'd':")
print(df)

# 3. Сортировка столбцов в обратном алфавитном порядке
df = df.reindex(columns=sorted(df.columns, reverse=True))

# Вывод окончательного датафрейма
print("\nПосле сортировки столбцов в обратном алфавитном порядке:")
print(df)


После обмена 'a' и 'c':
    a   b   c   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

После обмена 'b' и 'd':
    a   b   c   d   e
0   2   3   0   1   4
1   7   8   5   6   9
2  12  13  10  11  14
3  17  18  15  16  19

После сортировки столбцов в обратном алфавитном порядке:
    e   d   c   b   a
0   4   1   0   3   2
1   9   6   5   8   7
2  14  11  10  13  12
3  19  16  15  18  17


## Упражнение № 45

Измените настройки отображения `pandas` при выводе на печать датафрейма `df`, чтобы он показывал максимум 10 строк и 10 столбцов.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [52]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Изменение настроек отображения
pd.set_option('display.max_rows', 10)  # Максимум 10 строк
pd.set_option('display.max_columns', 10)  # Максимум 10 столбцов

# Вывод датафрейма
print(df)  # Датафрейм будет отображен с новыми настройками


   Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-U

## Упражнение № 46

Исключите вывод научной нотации типа 'e-03' в `df` и выведите до 4 чисел после запятой.

Пример входных данных:

```python
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df
#>          random
#> 0  3.474280e-03
#> 1  3.951517e-05
#> 2  7.469702e-02
#> 3  5.541282e-28
```

Пример выходных данных:

```python
#>    random
#> 0  0.0035
#> 1  0.0000
#> 2  0.0747
#> 3  0.0000
```

In [53]:
import pandas as pd
import numpy as np

# Создание датафрейма
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Изменение настроек отображения
pd.set_option('display.float_format', '{:.4f}'.format)  # Устанавливаем формат с 4 знаками после запятой

# Вывод датафрейма
print(df)


   random
0  0.0004
1  0.0891
2  0.0000
3  0.0013


## Упражнение № 47

Отформатируйте значения в столбце `'random'` из `df` в виде процентов.

Пример входных данных:

```python
df = pd.DataFrame(np.random.random(4), columns=['random'])
df
#>      random
#> 0    .689723
#> 1    .957224
#> 2    .159157
#> 3    .21082
```

Пример выходных данных:

```python
#>      random
#> 0    68.97%
#> 1    95.72%
#> 2    15.91%
#> 3    2.10%
```

In [54]:
import pandas as pd
import numpy as np

# Создание датафрейма
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Форматирование значений в столбце 'random' в проценты
df['random'] = (df['random'] * 100).map('{:.2f}%'.format)

# Вывод датафрейма
print(df)


   random
0  59.24%
1   4.65%
2  60.75%
3  17.05%


## Упражнение № 48

Из `df` отфильтруйте значения `Manufacturer`, `Model` и `Type` для каждой 20-й строки, начиная с 1-й (строка 0).

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


In [55]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Фильтрация для каждой 20-й строки, начиная с 1-й (0-индексация)
filtered_df = df.iloc[::20, [0, 1, 2]]  # 0, 1, 2 — это индексы столбцов 'Manufacturer', 'Model', 'Type'

# Вывод результирующего датафрейма
print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


## Упражнение № 49

В `df` замените `NaN` на `missing` в столбцах `Manufacturer`, `Model` и `Type` , создайте индекс как комбинацию этих трех столбцов и проверьте, является ли этот индекс первичным ключом.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
```

Пример выходных данных:

```
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
```

In [56]:
import pandas as pd

# Загрузка данных
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0, 1, 2, 3, 5])

# Замена NaN на 'missing' в указанных столбцах
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')

# Создание индекса на основе комбинации трех столбцов
df.set_index(['Manufacturer', 'Model', 'Type'], inplace=True)

# Проверка, является ли этот индекс первичным ключом
is_unique = df.index.is_unique

# Вывод результатов
print(df)
print("\nЯвляется ли индекс первичным ключом?", is_unique)


                              Min.Price  Max.Price
Manufacturer Model   Type                         
Acura        Integra Small      12.9000    18.8000
missing      Legend  Midsize    29.2000    38.7000
Audi         90      Compact    25.9000    32.3000
             100     Midsize        NaN    44.6000
BMW          535i    Midsize        NaN        NaN
...                                 ...        ...
Volkswagen   Eurovan Van        16.6000    22.7000
             Passat  Compact    17.6000    22.4000
             Corrado Sporty     22.9000    23.7000
Volvo        240     Compact    21.8000    23.5000
missing      850     Midsize    24.8000    28.5000

[93 rows x 2 columns]

Является ли индекс первичным ключом? True


## Упражнение № 50

Найти положение строки с 5-м наибольшим значением столбца `'a'` в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
```

In [57]:
import pandas as pd
import numpy as np

# Создание примера датафрейма
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10, -1), columns=list('abc'))

# Печатаем датафрейм для наглядности
print("Исходный датафрейм:\n", df)

# Находим индекс строки с 5-м наибольшим значением в столбце 'a'
position_5th_largest = df['a'].nlargest(5).index[-1]

# Выводим результат
print("\nПоложение строки с 5-м наибольшим значением столбца 'a':", position_5th_largest)


Исходный датафрейм:
     a   b   c
0   7  18   4
1  25  28  14
2  18  26   9
3  26  21   2
4  20  28  15
5  28   7  12
6  29   8  15
7   3  14  17
8   4  18   8
9   4   2   6

Положение строки с 5-м наибольшим значением столбца 'a': 4


## Упражнение № 51

В `ser` найдите положение 2-го наибольшего значения, превышающего среднее.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 100, 15))
```

In [58]:
import pandas as pd
import numpy as np

# Создаем пример серии из 15 случайных целых чисел от 1 до 100
ser = pd.Series(np.random.randint(1, 100, 15))

# Печатаем исходную серию для наглядности
print("Исходная серия:\n", ser)

# Рассчитываем среднее значение
mean_value = ser.mean()
print("\nСреднее значение:", mean_value)

# Отфильтровываем значения, превышающие среднее
filtered_values = ser[ser > mean_value]

# Находим 2-е наибольшее значение среди отфильтрованных значений
second_largest = filtered_values.nlargest(2).iloc[-1]

# Находим положение (индекс) 2-го наибольшего значения
position_second_largest = filtered_values[filtered_values == second_largest].index[0]

# Выводим результат
print("\nПоложение 2-го наибольшего значения, превышающего среднее:", position_second_largest)


Исходная серия:
 0     54
1      4
2     54
3     93
4     63
      ..
10    62
11    14
12    95
13    48
14    15
Length: 15, dtype: int32

Среднее значение: 50.8

Положение 2-го наибольшего значения, превышающего среднее: 3


## Упражнение № 52

Получите две последние строки `df`, сумма строк которых больше 100.

```python
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [59]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 60 случайными целыми числами от 10 до 40, размером 15x4
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Рассчитываем сумму по строкам
row_sums = df.sum(axis=1)

# Отфильтровываем строки, сумма которых больше 100
filtered_df = df[row_sums > 100]

# Получаем две последние строки из отфильтрованного DataFrame
result = filtered_df.tail(2)  # tail(2) возвращает последние 2 строки

# Выводим результат
print("\nДве последние строки с суммой больше 100:\n", result)


Исходный DataFrame:
      0   1   2   3
0   17  23  32  37
1   34  39  17  30
2   25  22  27  24
3   30  33  35  34
4   37  37  37  22
..  ..  ..  ..  ..
10  36  14  19  16
11  35  18  37  16
12  18  17  21  11
13  10  25  32  32
14  39  33  14  12

[15 rows x 4 columns]

Две последние строки с суммой больше 100:
      0   1   2   3
8   33  20  28  26
11  35  18  37  16


## Упражнение № 53

Замените все значения `ser`, находящиеся ниже 5%-ного и выше 95%-ного перцентиля, на соответствующие значения 5-го и 95-го перцентиля.

Пример входных данных:

```python
ser = pd.Series(np.logspace(-2, 2, 30))
```

In [60]:
import pandas as pd
import numpy as np

# Создаем Series
ser = pd.Series(np.logspace(-2, 2, 30))

# Находим 5-й и 95-й перцентиль
lower_percentile = ser.quantile(0.05)
upper_percentile = ser.quantile(0.95)

# Заменяем значения ниже 5% на 5%-ный перцентиль
ser[ser < lower_percentile] = lower_percentile

# Заменяем значения выше 95% на 95%-ный перцентиль
ser[ser > upper_percentile] = upper_percentile

# Выводим обработанную Series
print(ser)


0     0.0160
1     0.0160
2     0.0189
3     0.0259
4     0.0356
       ...  
25   28.0722
26   38.5662
27   52.9832
28   63.8767
29   63.8767
Length: 30, dtype: float64


## Упражнение № 54

Перестройте `df` в максимально возможный квадрат с удалением отрицательных значений. При необходимости отбросьте наименьшие значения. Порядок положительных чисел в результате должен остаться тем же, что и в исходном варианте.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
```

In [61]:
import pandas as pd
import numpy as np

# Создаем DataFrame с отрицательными и положительными значениями
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Убираем отрицательные значения и оставляем только положительные
positive_values = df[df >= 0].values.flatten()
positive_values = positive_values[~np.isnan(positive_values)]  # Удаляем NaN

# Определяем максимальный размер квадрата
n = int(np.sqrt(len(positive_values)))

# Создаем новый DataFrame, если есть положительные значения
if n > 0:
    square_df = pd.DataFrame(positive_values[:n * n].reshape(n, n))
else:
    square_df = pd.DataFrame()

# Выводим результат
print("\nКвадратный DataFrame:\n", square_df)


Исходный DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  23  14  44  26 -18 -20 -16  -7   6 -12
1  -6  21  30  42  31 -17   2  -6  22   8
2  15  -8  11  38   7  45  21  24  41  36
3 -15   7   7  23   9  41  41 -20   6  41
4 -18  49   6 -12  41  16  30  23   3  38
5  11  31  41  37  31  -9  18 -19 -18  35
6  38 -19 -19  33 -20  -2 -19  32  23  11
7  49  11  47  34  35  -4  17   3  48  49
8 -10  -5  38  49 -18  -1  38  15  -2  46
9  -2  -1  31  12  19  18 -20 -10  36  29

Квадратный DataFrame:
         0       1       2       3       4       5       6       7
0 23.0000 14.0000 44.0000 26.0000  6.0000 21.0000 30.0000 42.0000
1 31.0000  2.0000 22.0000  8.0000 15.0000 11.0000 38.0000  7.0000
2 45.0000 21.0000 24.0000 41.0000 36.0000  7.0000  7.0000 23.0000
3  9.0000 41.0000 41.0000  6.0000 41.0000 49.0000  6.0000 41.0000
4 16.0000 30.0000 23.0000  3.0000 38.0000 11.0000 31.0000 41.0000
5 37.0000 31.0000 18.0000 35.0000 38.0000 33.0000 32.0000 23.0000
6 11.0000 49.0000 11.0000 47.00

## Упражнение № 55

Поменяйте местами строки 1 и 2 в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5, -1))
```

In [62]:
import pandas as pd
import numpy as np

# Создаем DataFrame с примером входных данных
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Меняем местами строки 1 и 2
df.iloc[[1, 2]] = df.iloc[[2, 1]].values

# Выводим результат
print("\nDataFrame после замены строк 1 и 2:\n", df)


Исходный DataFrame:
     0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

DataFrame после замены строк 1 и 2:
     0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


## Упражнение № 56

Переверните строки датафрейма `df` (первая строка становится последней).

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5, -1))
```

In [63]:
import pandas as pd
import numpy as np

# Создаем DataFrame с примером входных данных
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Переворачиваем строки
reversed_df = df.iloc[::-1].reset_index(drop=True)

# Выводим результат
print("\nПеревернутый DataFrame:\n", reversed_df)


Исходный DataFrame:
     0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

Перевернутый DataFrame:
     0   1   2   3   4
0  20  21  22  23  24
1  15  16  17  18  19
2  10  11  12  13  14
3   5   6   7   8   9
4   0   1   2   3   4


## Упражнение № 57

Получите бинарный код для столбца `'a'` в датафрейме `df` и добавьте его в виде столбцов.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
```

Пример выходных данных:

```python
   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24
```

In [64]:
import pandas as pd
import numpy as np

# Создание исходного DataFrame
df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))

# Печать исходного DataFrame
print("Исходный DataFrame:\n", df)

# Преобразование столбца 'a' в бинарный код
# Для этого используем метод .apply() с форматом для строк
binary_codes = df['a'].apply(lambda x: f"{x:05b}")  # 5 бит для чисел от 0 до 24

# Создаем новый DataFrame из строк бинарного кода
binary_df = binary_codes.apply(lambda x: pd.Series(list(x))).astype(int)

# Переименовываем столбцы бинарного DataFrame для ясности
binary_df.columns = [f"bit_{i}" for i in range(binary_df.shape[1])]

# Объединяем бинарный DataFrame с исходным, добавляя к правому краю
result_df = pd.concat([binary_df, df.iloc[:, 1:]], axis=1)

# Печать итогового DataFrame
print("\nИтоговый DataFrame с бинарными столбцами:\n", result_df)


Исходный DataFrame:
     a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

Итоговый DataFrame с бинарными столбцами:
    bit_0  bit_1  bit_2  bit_3  bit_4   b   c   d   e
0      0      0      0      0      0   1   2   3   4
1      0      0      1      0      1   6   7   8   9
2      0      1      0      1      0  11  12  13  14
3      0      1      1      1      1  16  17  18  19
4      1      0      1      0      0  21  22  23  24


## Упражнение № 58

Получите название столбца с наибольшим количеством строчных максимумов в `df`.

```python
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
```

In [65]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 10 строками и 4 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))

# Печать исходного DataFrame
print("Исходный DataFrame:\n", df)

# Находим индексы столбцов, в которых находятся строчные максимумы
# Сначала мы берем максимальные значения по строкам
row_maxes = df.max(axis=1)

# Теперь создадим маску, где максимальное значение равно значению в соответствующем столбце
# и подсчитаем количество максимумов для каждого столбца
max_count = (df == row_maxes.values[:, None]).sum()

# Находим столбец с максимальным количеством строчных максимумов
column_with_max_maxes = max_count.idxmax()

# Печатаем результат
print("\nСтолбец с наибольшим количеством строчных максимумов:", column_with_max_maxes)


Исходный DataFrame:
     0   1   2   3
0  23  31  94  42
1  99   7  16  90
2  60   2   1  48
3  12  69  37  32
4   9  99  19  48
5  80   3  20  24
6  54  33  24  75
7  72  36  38  84
8  99  89  99  25
9  93  18  82  66

Столбец с наибольшим количеством строчных максимумов: 0


## Упражнение № 59

Создать новый столбец, в каждой строке которого будет указан номер строки, ближайшей по евклидову расстоянию к данной строке.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df
#     p   q   r   s
# a  57  77  13  62
# b  68   5  92  24
# c  74  40  18  37
# d  80  17  39  60
# e  93  48  85  33
# f  69  55   8  11
# g  39  23  88  53
# h  63  28  25  61
# i  18   4  73   7
# j  79  12  45  34
```

Пример выходных данных:

```python
df
#    p   q   r   s nearest_row   dist
# a  57  77  13  62           i  116.0
# b  68   5  92  24           a  114.0
# c  74  40  18  37           i   91.0
# d  80  17  39  60           i   89.0
# e  93  48  85  33           i   92.0
# f  69  55   8  11           g  100.0
# g  39  23  88  53           f  100.0
# h  63  28  25  61           i   88.0
# i  18   4  73   7           a  116.0
# j  79  12  45  34           a   81.0
```

In [66]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 10 строками и 4 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Функция для вычисления евклидова расстояния
def euclidean_distance(row1, row2):
    return np.sqrt(np.sum((row1 - row2) ** 2))

# Списки для хранения результатов
nearest_rows = []
distances = []

# Для каждой строки находим ближайшую строку
for i in range(len(df)):
    current_row = df.iloc[i]
    # Находим расстояния до всех остальных строк
    dists = []
    for j in range(len(df)):
        if i != j:
            dist = euclidean_distance(current_row, df.iloc[j])
            dists.append((df.index[j], dist))
    # Находим ближайшую строку и ее расстояние
    nearest_row, min_dist = min(dists, key=lambda x: x[1])
    nearest_rows.append(nearest_row)
    distances.append(min_dist)

# Добавляем новые столбцы в DataFrame
df['nearest_row'] = nearest_rows
df['dist'] = distances

# Печатаем результат
print(df)


    p   q   r   s nearest_row    dist
a  54  35  80  61           e 25.0998
b  41  33  68  33           e 32.0780
c  14  21  48  20           d 24.5357
d   8   7  67  17           c 24.5357
e  33  48  76  59           a 25.0998
f  86  22  30  38           j 49.9500
g  51  54   8  27           j 45.1331
h  27  98  21  30           g 51.8652
i  97  28  64  97           a 58.7367
j  69  61  48  19           g 45.1331


## Упражнение № 60

Вычислите максимально возможное абсолютное значение корреляции каждого столбца с другими столбцами в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
```

In [67]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 8 строками и 10 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

# Создаем DataFrame для хранения максимальных абсолютных корреляций
max_abs_correlation = {}

# Вычисляем корреляцию для каждого столбца
correlation_matrix = df.corr()

# Проходим по каждому столбцу и находим максимальное абсолютное значение корреляции
for column in df.columns:
    max_corr = correlation_matrix[column].drop(column).abs().max()  # исключаем сам столбец
    max_abs_correlation[column] = max_corr

# Превращаем словарь в DataFrame для удобного отображения
max_abs_correlation_df = pd.DataFrame(max_abs_correlation.items(), columns=['Column', 'Max Abs Correlation'])

# Печатаем результат
print(max_abs_correlation_df)


  Column  Max Abs Correlation
0      p               0.7050
1      q               0.8106
2      r               0.7808
3      s               0.7992
4      t               0.7528
5      u               0.8106
6      v               0.7485
7      w               0.5501
8      x               0.7808
9      y               0.7992


## Упражнение № 61

Вычислите минимум-максимум для каждой строки `df`.

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [68]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 8 строками и 10 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Вычисляем минимум и максимум для каждой строки
min_values = df.min(axis=1)  # Минимум по строкам
max_values = df.max(axis=1)  # Максимум по строкам

# Создаём DataFrame с результатами
result = pd.DataFrame({'Min': min_values, 'Max': max_values})

# Печатаем результат
print("\nМинимум и максимум для каждой строки:\n", result)


Исходный DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  63  62  22  58  58  86  49  52  42  70
1  15  54  60  97   8  53  60   5  68   6
2  96  94  47  99  55  40  52  16  13  30
3  19  17  63  19  92  58  55  90  90  62
4  23   9  12   1  58   1  34  96  48  89
5   1  16  61  64  63  69  22  93  67  76
6  26  16  51  86  57  29  78  92  69  47
7  94  62  69  76  16  90  90  48  85  39

Минимум и максимум для каждой строки:
    Min  Max
0   22   86
1    5   97
2   13   99
3   17   92
4    1   96
5    1   93
6   16   92
7   16   94


## Упражнение № 62

Создайте новый столбец `penultimate`, который содержит второе по величине значение каждой строки `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [69]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 8 строками и 10 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Функция для нахождения второго по величине значения
def second_largest(row):
    return row.nlargest(2).min()

# Применяем функцию ко всем строкам и создаем новый столбец 'penultimate'
df['penultimate'] = df.apply(second_largest, axis=1)

# Печатаем результат
print("\nDataFrame с новым столбцом 'penultimate':\n", df)


Исходный DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  33  94  23  10  69  34  52  95  10  19
1  58  96   1  69   4  16  24  80   2  92
2  32  91  84  24  12  50  35  33  33  61
3  51  43  12  67  65  33  40  74  43  44
4  29  13  12  95  46   2  35  87  81  90
5   8  93  26  74  90  34   7  68  58  75
6  29  36  89  21  36  10  73  24  64  99
7  49  99  36  82  96  24  23  62  96  37

DataFrame с новым столбцом 'penultimate':
     0   1   2   3   4  ...   6   7   8   9  penultimate
0  33  94  23  10  69  ...  52  95  10  19           94
1  58  96   1  69   4  ...  24  80   2  92           92
2  32  91  84  24  12  ...  35  33  33  61           84
3  51  43  12  67  65  ...  40  74  43  44           67
4  29  13  12  95  46  ...  35  87  81  90           90
5   8  93  26  74  90  ...   7  68  58  75           90
6  29  36  89  21  36  ...  73  24  64  99           89
7  49  99  36  82  96  ...  23  62  96  37           96

[8 rows x 11 columns]


# Упражнение № 63

1. Нормализуйте все столбцы `df`, вычитая среднее значение столбца и деля его на стандартное отклонение.
2. Произведите ранжирование всех столбцов `df` таким образом, чтобы минимальное значение в каждом столбце было равно 0, а максимальное — 1.

Не используйте внешние пакеты типа `sklearn`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [70]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 8 строками и 10 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# 1. Нормализация
normalized_df = (df - df.mean()) / df.std()

# Печатаем результат нормализации
print("\nНормализованный DataFrame:\n", normalized_df)

# 2. Ранжирование
ranked_df = (normalized_df - normalized_df.min()) / (normalized_df.max() - normalized_df.min())

# Печатаем результат ранжирования
print("\nРанжированный DataFrame:\n", ranked_df)


Исходный DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  12  55  13  23  89  99  30  17  62  84
1  89  86  13  59  19  49  12  61  19  76
2   9  71  28  78  95  52  83  16  69  99
3  12  25  52  85  53  23  16  57  39  53
4  42  58  39  14  95   5  35  87  93  75
5  18  76   9  74  58  17   7  46  13  40
6  42   9  50  27  66   5  29  37  38  83
7   8  65  86  17  71  89  45   4  36  70

Нормализованный DataFrame:
         0       1       2       3       4       5       6       7       8  \
0 -0.6077 -0.0239 -0.8868 -0.8078  0.8062  1.5510 -0.0881 -0.8520  0.5925   
1  2.1448  1.1624 -0.8868  0.3976 -1.9134  0.1815 -0.8343  0.7348 -1.0124   
2 -0.7149  0.5884 -0.3147  1.0339  1.0393  0.2636  2.1091 -0.8881  0.8538   
3 -0.6077 -1.1720  0.6007  1.2683 -0.5925 -0.5307 -0.6685  0.5906 -0.2659   
4  0.4647  0.0909  0.1049 -1.1092  1.0393 -1.0237  0.1192  1.6725  1.7496   
5 -0.3932  0.7797 -1.0394  0.8999 -0.3982 -0.6951 -1.0416  0.1938 -1.2364   
6  0.4647 -1.7843  0.5245 -0.6739

## Упражнение № 64

Вычислите корреляцию каждой строки `df` с последующей строкой.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [71]:
import pandas as pd
import numpy as np

# Создаем DataFrame с 8 строками и 10 столбцами случайных чисел от 1 до 100
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

# Печатаем исходный DataFrame
print("Исходный DataFrame:\n", df)

# Список для хранения корреляций
correlation_list = []

# Вычисляем корреляцию для каждой пары соседних строк
for i in range(len(df) - 1):
    correlation = df.iloc[i].corr(df.iloc[i + 1])  # Корреляция текущей строки с следующей
    correlation_list.append(correlation)

# Превращаем список в DataFrame для удобного отображения
correlation_df = pd.DataFrame(correlation_list, columns=['Correlation'], index=df.index[:-1])

# Печатаем результат
print("\nКорреляция каждой строки с последующей:\n", correlation_df)


Исходный DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  31  19  61  54  39  91  74  90  19  39
1  67  45  13  92  58  20  92  72  61  39
2   1   3  77  92  62  63  25  56  33  38
3   6  58  44  45  32  45  61  47  21  80
4  85  75  36  99  19  20  57  18  47  49
5  14  15  31   1  54   3  16  87  57  75
6  12  74  96  16  72  76  24  28   8  92
7  36  90   8  58  60  50  28  92  41  64

Корреляция каждой строки с последующей:
    Correlation
0      -0.0241
1      -0.1094
2       0.1165
3      -0.0991
4      -0.5510
5       0.1007
6       0.0154


## Упражнение № 65

Замените все значения в обеих диагоналях `df` на 0.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df
#     0   1   2   3   4   5   6   7   8   9
# 0  11  46  26  44  11  62  18  70  68  26
# 1  87  71  52  50  81  43  83  39   3  59
# 2  47  76  93  77  73   2   2  16  14  26
# 3  64  18  74  22  16  37  60   8  66  39
# 4  10  18  39  98  25   8  32   6   3  29
# 5  29  91  27  86  23  84  28  31  97  10
# 6  37  71  70  65   4  72  82  89  12  97
# 7  65  22  97  75  17  10  43  78  12  77
# 8  47  57  96  55  17  83  61  85  26  86
# 9  76  80  28  45  77  12  67  80   7  63
```

Пример выходных данных:

```python
#     0   1   2   3   4   5   6   7   8   9
# 0   0  46  26  44  11  62  18  70  68   0
# 1  87   0  52  50  81  43  83  39   0  59
# 2  47  76   0  77  73   2   2   0  14  26
# 3  64  18  74   0  16  37   0   8  66  39
# 4  10  18  39  98   0   0  32   6   3  29
# 5  29  91  27  86   0   0  28  31  97  10
# 6  37  71  70   0   4  72   0  89  12  97
# 7  65  22   0  75  17  10  43   0  12  77
# 8  47   0  96  55  17  83  61  85   0  86
# 9   0  80  28  45  77  12  67  80   7   0
```


In [72]:
import pandas as pd
import numpy as np

# Создаем DataFrame с примером входных данных
df = pd.DataFrame(np.random.randint(1, 100, 100).reshape(10, -1))

# Печатаем исходный DataFrame для наглядности
print("Исходный DataFrame:\n", df)

# Заменяем значения на главной диагонали на 0
np.fill_diagonal(df.values, 0)

# Заменяем значения на побочной диагонали на 0
np.fill_diagonal(np.fliplr(df.values), 0)

# Выводим результат
print("\nDataFrame после замены диагоналей на 0:\n", df)


Исходный DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  27  63  17  73  33  84  77  92  29  13
1  46  35   6  82  69  47  25  66  10  56
2  30   5  33  65  18  96  49  11  85  26
3  63  89  86  59  27  49  77  33  98  99
4   1  21  55   6  92  81  69  95   5   3
5  53  23  53  37  74  74  83  17  85  78
6  73   1  51  45  77   4  62  65  32  34
7  92  95  72  39  26  34  54   3  50  12
8  65  54   5  94  94  57  17  47  23  79
9  85  14  66  75  51  38  64  98  38  50

DataFrame после замены диагоналей на 0:
     0   1   2   3   4   5   6   7   8   9
0   0  63  17  73  33  84  77  92  29   0
1  46   0   6  82  69  47  25  66   0  56
2  30   5   0  65  18  96  49   0  85  26
3  63  89  86   0  27  49   0  33  98  99
4   1  21  55   6   0   0  69  95   5   3
5  53  23  53  37   0   0  83  17  85  78
6  73   1  51   0  77   4   0  65  32  34
7  92  95   0  39  26  34  54   0  50  12
8  65   0   5  94  94  57  17  47   0  79
9   0  14  66  75  51  38  64  98  38   0


## Упражнение № 66

Из `df_grouped` получите в виде датафрейма группу, относящуюся к `apple`.

Пример входных данных:

```python
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
```

Пример выходных данных

```
    col1      col2  col3
0  apple  0.673434     7
3  apple  0.182348    14
6  apple  0.050457     3
```

In [74]:
import pandas as pd
import numpy as np

# Создаем DataFrame с примером входных данных
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

# Группируем по 'col1'
df_grouped = df.groupby(['col1'])

# Получаем группу, относящуюся к 'apple', передавая имя в виде кортежа
apple_group = df_grouped.get_group(('apple',)).reset_index(drop=True)

# Выводим датафрейм для группы apple
print(apple_group)


    col1   col2  col3
0  apple 0.7689     6
1  apple 0.6208    10
2  apple 0.5796     3


## Упражнение № 67

В `df` найдите второе по величине значение `taste` для `banana`.

Пример входных данных:

```python
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
```

In [75]:
import pandas as pd
import numpy as np

# Создаем DataFrame с примером входных данных
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Отфильтровать строки с banana
banana_ratings = df[df['fruit'] == 'banana']['rating']

# Получаем уникальные значения и сортируем их по убыванию
second_best_rating = banana_ratings.unique()

# Проверим, что в выборке достаточно уникальных значений
if len(second_best_rating) >= 2:
    # Сортируем и выбираем второе по величине
    second_highest = np.sort(second_best_rating)[-2]
    print(f"Второе по величине значение rating для banana: {second_highest}")
else:
    print("Недостаточно уникальных значений для banana.")


Второе по величине значение rating для banana: 0.17231987120162984


## Упражнение № 68

В `df` вычислите среднюю цену `Price` каждого фрукта `Fruit`, сохраняя фрукт как еще один столбец вместо индекса.

Пример входных данных:

```python
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
```

In [76]:
import pandas as pd
import numpy as np

# Создаем DataFrame с примером входных данных
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Вычисляем среднюю цену для каждого фрукта
average_price = df.groupby('fruit')['price'].mean().reset_index()

# Переименуем колонки для ясности (по желанию)
average_price.columns = ['fruit', 'average_price']

# Выводим результат
print(average_price)


    fruit  average_price
0   apple         5.0000
1  banana         0.6667
2  orange         9.3333


## Упражнение № 69

Объединить датафреймы `df1` и `df2` по признакам `fruit-pazham` и `weight-kilo`.

Пример входных данных:

```python
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
```

In [77]:
import pandas as pd
import numpy as np

# Создаем датафреймы с примером входных данных
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

# Объединяем датафреймы df1 и df2
merged_df = pd.merge(df1, df2, left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'])

# Выводим результат
print(merged_df)


    fruit weight  price_x  pazham  kilo  price_y
0   apple   high        3   apple  high        6
1  orange    low       14  orange   low       13
2   apple   high       14   apple  high        6
3  orange    low        5  orange   low       13
4   apple   high       13   apple  high        6
5  orange    low       11  orange   low       13


## Упражнение № 70

Создайте в `df` два новых столбца, один из них — `lag1` (сдвиг столбца `a` вниз на 1 строку) столбца 'a', а другой — `lead1` (сдвиг столбца `b` вверх на 1 строку).

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

    a   b   c   d
0  66  34  76  47
1  20  86  10  81
2  75  73  51  28
3   1   1   9  83
4  30  47  67   4
```

Пример выходных данных:

```python
    a   b   c   d  a_lag1  b_lead1
0  66  34  76  47     NaN     86.0
1  20  86  10  81    66.0     73.0
2  75  73  51  28    20.0      1.0
3   1   1   9  83    75.0     47.0
4  30  47  67   4     1.0      NaN
```

In [78]:
import pandas as pd
import numpy as np

# Создаем пример DataFrame
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns=list('abcd'))

# Печатаем исходный датафрейм
print("Исходный DataFrame:\n", df)

# Создаем столбцы a_lag1 и b_lead1
df['a_lag1'] = df['a'].shift(1)  # Сдвиг столбца 'a' вниз на 1 строку
df['b_lead1'] = df['b'].shift(-1) # Сдвиг столбца 'b' вверх на 1 строку

# Печатаем результат
print("\nDataFrame с новыми столбцами 'a_lag1' и 'b_lead1':\n", df)


Исходный DataFrame:
     a   b   c   d
0  14  59  56   7
1   3  23  18  38
2  99  15  64  89
3  28  74  39  57
4  17  86  90  44

DataFrame с новыми столбцами 'a_lag1' и 'b_lead1':
     a   b   c   d  a_lag1  b_lead1
0  14  59  56   7     NaN  23.0000
1   3  23  18  38 14.0000  15.0000
2  99  15  64  89  3.0000  74.0000
3  28  74  39  57 99.0000  86.0000
4  17  86  90  44 28.0000      NaN


## Упражнение № 71

Получите частоты уникальных значений по всему датафрейму `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
```

In [79]:
import pandas as pd
import numpy as np

# Создание примера DataFrame
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns=list('abcd'))

# Печатаем исходный DataFrame
print("Исходный DataFrame:\n", df)

# Получение частот уникальных значений для всего DataFrame
value_counts = df.apply(pd.Series.value_counts).fillna(0)

# Печатаем частоты уникальных значений
print("\nЧастоты уникальных значений в DataFrame:\n", value_counts)


Исходный DataFrame:
    a  b  c  d
0  9  1  4  9
1  4  3  9  2
2  4  6  2  8
3  8  1  3  9
4  5  6  4  2

Частоты уникальных значений в DataFrame:
        a      b      c      d
1 0.0000 2.0000 0.0000 0.0000
2 0.0000 0.0000 1.0000 2.0000
3 0.0000 1.0000 1.0000 0.0000
4 2.0000 0.0000 2.0000 0.0000
5 1.0000 0.0000 0.0000 0.0000
6 0.0000 2.0000 0.0000 0.0000
8 1.0000 0.0000 0.0000 1.0000
9 1.0000 0.0000 1.0000 2.0000


## Упражнение № 72

Разделите столбец `row` в `df` так, чтобы сформировать датафрейм с 3 столбцами, как показано в примере выходных данных. 

Пример входных данных:

```python
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
#>                         row
#> 0          STD, City\tState
#> 1  33, Kolkata\tWest Bengal
#> 2   44, Chennai\tTamil Nadu
#> 3  40, Hyderabad\tTelengana
#> 4  80, Bangalore\tKarnataka
```

Пример выходных данных:

```
0 STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
```


In [89]:
import pandas as pd

# Исходные данные
df = pd.DataFrame([
    "STD, City    State",
    "33, Kolkata    West Bengal",
    "44, Chennai    Tamil Nadu",
    "40, Hyderabad    Telengana",
    "80, Bangalore    Karnataka"
], columns=['row'])

# Разделим строку по запятой и создадим новые столбцы
df_split = df['row'].str.split(',', expand=True)

# Убираем лишние пробелы
df_split = df_split.apply(lambda x: x.str.strip())

# Проверяем количество столбцов
print(df_split)

# Переименовываем столбцы (если их 3)
if df_split.shape[1] == 3:
    df_split.columns = ['STD', 'City', 'State']
else:
    print("Количество столбцов не соответствует ожиданиям!")

# Выводим результат
print(df_split)


     0                       1
0  STD           City    State
1   33  Kolkata    West Bengal
2   44   Chennai    Tamil Nadu
3   40  Hyderabad    Telengana
4   80  Bangalore    Karnataka
Количество столбцов не соответствует ожиданиям!
     0                       1
0  STD           City    State
1   33  Kolkata    West Bengal
2   44   Chennai    Tamil Nadu
3   40  Hyderabad    Telengana
4   80  Bangalore    Karnataka
